services:
  api-gateway:
    build: ./api-gateway
    ports: ["8080:8080"]
    depends_on: [user-service]

  auth-service:
    build: ./user-service
    ports: ["8081:8081"]
    depends_on: [user-db]
    environment:
      DB_URL: postgres://user:pass@user-db:5432/users

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: pass

  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: orders
      POSTGRES_PASSWORD: pass
