services:
  api-gateway:
    build:
      context: .
      dockerfile: ./DockerGateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/bin
    environment:
      - SERVICE_NAME=api-gateway
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: DockerService
      args:
        SERVICE_NAME: auth
    container_name: auth
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/bin
    environment:
      - SERVICE_NAME=auth
    depends_on:
      db:
        condition: service_healthy

  google:
    build:
      context: .
      dockerfile: DockerService
      args:
        SERVICE_NAME: google
    container_name: google
    ports:
      - "8082:8080"
    volumes:
      - .:/app
      - /app/bin
    environment:
      - SERVICE_NAME=google
    depends_on:
      db:
        condition: service_healthy

  middle:
    build:
      context: .
      dockerfile: DockerService
      args:
        SERVICE_NAME: middle
    container_name: middle
    ports:
      - "8083:8080"
    volumes:
      - .:/app
      - /app/bin
    environment:
      - SERVICE_NAME=middle
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
