services:
  api-gateway:
    build:
      context: .
      dockerfile: ./DockerGateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/bin
    environment:
      - SERVICE_NAME=api-gateway

  auth:
    build:
      context: .
      dockerfile: DockerService
      args:
        SERVICE_NAME: auth
    container_name: auth
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/bin
    environment:
      - SERVICE_NAME=auth
