name: Deploy Backend Services

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'docker-compose.prod.yml'
      - 'DockerGateway.prod'
      - 'DockerService.prod'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    env:
      DEPLOY_IP: ${{ vars.LINODE_IP }}
      DEPLOY_USER: ${{ vars.DEPLOY_USER }}
    steps:
      - name: Add SSH Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $DEPLOY_IP >> ~/.ssh/known_hosts

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_IP "
            cd /var/www/pvt-backend &&
            git pull &&
            bash scripts/generate-compose.prod.sh &&
            docker compose -f docker-compose.prod.yml up --build -d
          "
